-- MySQL Script generated by MySQL Workbench
-- Sat Jun  2 00:50:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema appdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema appdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appdb` DEFAULT CHARACTER SET utf8 ;
USE `appdb` ;

-- -----------------------------------------------------
-- Table `appdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripción` VARCHAR(500) NULL,
  `ubicacion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`landmark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`landmark` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `id_detalle` INT NULL,
  `latitud` VARCHAR(45) NULL,
  `longitud` VARCHAR(45) NULL,
  `calificacion` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_detalle_idx` (`id_detalle` ASC),
  CONSTRAINT `id_detalle`
    FOREIGN KEY (`id_detalle`)
    REFERENCES `appdb`.`detalles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`historial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_users` INT NULL,
  `id_landmark` INT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `id_users_idx` (`id_users` ASC),
  INDEX `id_landmark_idx` (`id_landmark` ASC),
  CONSTRAINT `id_users`
    FOREIGN KEY (`id_users`)
    REFERENCES `appdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_landmark`
    FOREIGN KEY (`id_landmark`)
    REFERENCES `appdb`.`landmark` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`recomendacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`recomendacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_historial` INT NULL,
  `id_landmark` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_historial_idx` (`id_historial` ASC),
  INDEX `id_landmark_idx` (`id_landmark` ASC),
  CONSTRAINT `id_historial`
    FOREIGN KEY (`id_historial`)
    REFERENCES `appdb`.`historial` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_landmark_recomendacion`
    FOREIGN KEY (`id_landmark`)
    REFERENCES `appdb`.`landmark` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
